### ISSUE TITLE
Untracked files are added

### ISSUE THREAD

**Issue by thiagofigueiro** [joshuapaling/safe_update#1]
If you have untracked files in your project directory they will be included with the first commit that `safe_update` does.

I only noticed because I had a database dump sitting in my directory and I got this error when pushing to github:

`remote: error: File database.dump is 338.44 MB; this exceeds GitHub's file size limit of 100.00 MB`

**Comment by joshuapaling** [comment]
Yep. It does `git add -A`. I'll change it to only stage gemfile.lock, and I'll also make it so it won't run if you've got existing staged changes.

**Comment by joshuapaling** [comment]
Released v0.1.1. It'll only stage your gemfile.lock, and it'll exit with 1 (and a message) if you have staged changes, or if you have unstaged changes to gemfile.lock.

Thanks for the bug report!
