### ISSUE TITLE
Feature request: optionally run `git push` every N updates

### ISSUE THREAD

**Issue by thiagofigueiro** [joshuapaling/safe_update#4]
This is useful if you want your CI to run tests every N commits.  Very useful to run after-hours when you won't block other people's builds.  It will save some time the next day when you're running git bisect as many of the commits will have already been tested.

**Comment by joshuapaling** [comment]
Ah yeah, that sounds good. Hassle me again (here or twitter/slack/wherever) if I haven't made any progress on this within a week.

**Comment by joshuapaling** [comment]
This is done in v0.2.0, which I've just released. Also, wouldn't mind your opinion on https://github.com/joshuapaling/safe_update/issues/7 - do you run in a branch? Would you like safe_update to be able to just create a branch for you? Or not a useful feature for your workflow?

**Comment by thiagofigueiro** [comment]
awesome stuff! this week I'm merging an upgrade to rails 4.2 I did and, next-up, I'll do gems.  Will run it overnight with `-p 1`.
