### ISSUE TITLE
Possibly make an option to automatically create a branch, and maybe merge it at the end, too?

### ISSUE THREAD

**Issue by joshuapaling** [joshuapaling/safe_update#7]

**Comment by joshuapaling** [comment]
Something like -b or --branch, where you can specify a name, or have it create a branch with a default name.

**Comment by thiagofigueiro** [comment]
I typically run safe_update in a branch. In my own workflow it would probably be most useful if it were the default behaviour otherwise I'll forget and just `git branch` myself.

**Comment by joshuapaling** [comment]
Yeah I agree. Probably best to do it in a branch, but not merge at the end. Then, people can do what they want - eg fast forward merge or whatever.

**Comment by thiagofigueiro** [comment]
Here's another idea.

If branching by default you could check to see what branch they're in.  If they're on master the default is to create a new branch.  If not on master the default is to not create a branch.

In any case, I agree merging by default would defeat the purpose.

**Comment by joshuapaling** [comment]
I decided the simplest option for now is to just create the branch manually, but I've added a section in the doco with one-liners for creating a branch and running safe_update, so it's easy to copy/paste: https://github.com/joshuapaling/safe_update#recommended-workflow

**Comment by thiagofigueiro** [comment]
KISS FTW. 👍
